### ISSUE TITLE
Support llvm-mingw

### ISSUE THREAD

**Issue by iahun2** [annacrombie/muon#52]
Related: #48.

I'm trying to build this project: https://github.com/franko/fox

muon setup always fails because it can't find the libraries, even though these libraries are always a part of a MinGW-w64 distribution, including llvm-mingw.

This is the problematic line:

https://github.com/franko/fox/blob/ccd6cf3b6e215d818480478b67f40be674e51319/meson.build#L49

cc.find_library doesn't work with llvm-mingw.

The very same project builds fine with a pure GNU Toolchain like winlibs.com's MinGW-w64 distribution.

**Comment by vtorri** [comment]
muon -v setup etc... for verbose mode. maybe there will be some useful information

**Comment by vtorri** [comment]
I've update the muon git (it was updated yesterday with important changes) and modified it so that it displays the files that are searched. My system is MSYS2. I don't know which terminal you use. I tried these ones. I have cloned muon and fox in the same dir

1. terminal MSYS2 Mingw64. I run `pacman -S mingw-w64-x86_64-curl mingw-w64-x86_64-libarchive mingw-w64-x86_64-pkgconf mingw-w64-x86_64-ninja` for the dependencies. Then I run
```
cd muon
CC="gcc" CFLAGS="-g3 -ggdb3 -std=c99" ./bootstrap.sh build
CC="gcc" CFLAGS="-g3 -ggdb3 -std=c99" ./build/muon.exe setup build_muon_gcc
cd ../fox
../muon_github/build_muon_gcc/muon.exe setup builddir
```
2. terminal MSYS2 Clang64. I run `pacman -S mingw-w64-clang-x86_64-curl mingw-w64-clang-x86_64-libarchive mingw-w64-clang-x86_64-pkgconf mingw-w64-clang-x86_64-ninja` for the dependencies. Then I run
```
cd muon
CC="clang" CFLAGS="-g3 -ggdb3 -std=c99" ./bootstrap.sh build
CC="clang" CFLAGS="-g3 -ggdb3 -std=c99" ./build/muon.exe setup build_muon_clang
cd ../fox
../muon/build_muon_clang/muon.exe setup -Denv.CC=clang -Denv.CXX=clang++ -Denv.LD=lld builddir
```

For both methods, it works for me

**Comment by vtorri** [comment]
btw, I have added a PR for CI with clang 32 and 64 bits

**Comment by iahun2** [comment]
I don't use MSYS2. I use a pure Win32 environment: llvm-mingw + ConEmu.

**Comment by vtorri** [comment]
pure win32 == console with cmd interpreter (in which muon can be compiled). ConEmu is like msys2 or mintty, a terminal emulator (CONsoleEMUlator, see the ConEmu doc).
MSYS2 has the advantage of having a package manager. Far simpler for development.
But do what you prefer, of course :)
